name: Build Checklists

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: alexnj/aviation-checklist-actions/.github/workflows/compile.yml@main
    with:
      efis-editor-patch: efis-editor.patch
