name: Build Checklists

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Checkout EFIS file format editor repository
        uses: actions/checkout@v4
        with:
          repository: rdamazio/efis-editor
          path: efis-editor

      - name: Install efis-editor dependencies
        run: npm install
        working-directory: efis-editor

      - name: Patch EFIS-editor with specific changes
        run: git apply ../efis-editor.patch
        working-directory: efis-editor

      - name: Generate efis-editor protobuf files
        run: npm run genproto
        working-directory: efis-editor

      - name: Generate efis-editor keys
        run: npm run genkeys
        working-directory: efis-editor

      - name: Install compiler dependencies
        run: npm install
        working-directory: compiler

      - name: Compile Compiler Typescript
        working-directory: efis-editor
        run: npx tsc ../compiler/*.ts --module commonjs --esModuleInterop --target es2022 --lib es2022,dom --skipLibCheck

      - name: Convert Checklist JSONs to EFIS
        run: node compiler/compiler.js

      - name: Setup gh actions artifact client
        uses: lhotari/gh-actions-artifact-client@v2

      - name: Upload artifacts
        run: |
          mkdir output-release
          find output -type f | while read -r file; do
            name=${file##*checklists/}
            final_name=${name//\//\.}
            echo "Uploading $name, file: $final_name"
            cp "$file" "output-release/$final_name"
            cat "$file" | gh-actions-artifact-client.js upload "${final_name}" --retentionDays=7
          done

      - uses: 'softprops/action-gh-release@v1'
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: 'latest'
          name: 'Automatic Release Build'
          body_path: 'output.md'
          prerelease: true
          files: |
            output-release/*
